[mcp_servers.agent-fix-tools]
args = [
    "-m",
    "mcp_servers.agent_fix_tools.server",
]
command = "/Users/bryce_ni/wit/agent-fix/.venv/bin/python"
env_vars = ["PROJECT_CONFIG"]

[mcp_servers.chrome-devtools]
args = [
    "-y",
    "chrome-devtools-mcp@latest",
]
command = "npx"
